### ISSUE TITLE
无障碍中只有AutoJs，没有main

### ISSUE THREAD

**Issue by willbeevil** [ErazerControl/2019double11#11]
double11v1.1.0beta版本
系统是Flyme，已root，已授予该apk权限
但无障碍中没有main，只有AutoJs，所以尝试开启AutoJs
但无法正常执行，页面会自动转到tb再转到辅助功能设置，然后停止
软件日志显示运行结束
且，点击设置，软件会闪退

**Comment by ErazerControl** [comment]
> double11v1.1.0beta版本
> 系统是Flyme，已root，已授予该apk权限
> 但无障碍中没有main，只有AutoJs，所以尝试开启AutoJs
> 但无法正常执行，页面会自动转到tb再转到辅助功能设置，然后停止
> 软件日志显示运行结束
> 且，点击设置，软件会闪退

meizu的手机确实会这样，每次启动应用都需要开启无障碍模式导致脚本运行失败。需要一直对该应用开启辅助功能，可以这样尝试一下
●、应用需保持长驻后台运行，否则「服务」即刻关闭，办法如下：
①、手机管家→手机加速→设置→手机加速白名单→“对应 App”→添加白名单；
②、手机管家→权限管理→自启动管理→“对应 App”→允许自启动；
③、手机管家→省电模式→待机耗电管理→“对应 App”→保持运行；
④、上滑多任务→“对应 App”→长按加锁。(此步亦可忽略)
⑤、打开“对应 App”之后前往设置→辅助功能→无障碍→“对应 App”→开启服务。
※、避免使用手机管家“一键优化”功能，或关闭部分应用自启动，可以分类清理优化。
[出自这里](https://bbs.meizu.cn/thread-7616277-1-1.html)

**Comment by ErazerControl** [comment]
新版本v1.2.0已经解决该问题
