### ISSUE TITLE
为什么遇到有视频的就自动停止了

### ISSUE THREAD

**Issue by hyy34** [ErazerControl/2019double11#16]
15s的下滑预览没什么问题，但是有时候会进入带广告视频的界面，不知道进的是什么地方，然后看完视频就自动停止了。。然后app出个叹号。进app上面提示脚本停止。。重启开启后，还是这样。

**Comment by ErazerControl** [comment]
> 15s的下滑预览没什么问题，但是有时候会进入带广告视频的界面，不知道进的是什么地方，然后看完视频就自动停止了。。然后app出个叹号。进app上面提示脚本停止。。重启开启后，还是这样。

我这里还没遇到过此问题，所以很难调试到..

**Comment by ErazerControl** [comment]
> 15s的下滑预览没什么问题，但是有时候会进入带广告视频的界面，不知道进的是什么地方，然后看完视频就自动停止了。。然后app出个叹号。进app上面提示脚本停止。。重启开启后，还是这样。

已经定位到问题了，明天将会更新代码哈~
