### ISSUE TITLE
提示脚本需要安卓7.0才能使用

### ISSUE THREAD

**Issue by willbeevil** [ErazerControl/2019double11#21]
double11v2.0.0,
到店铺后提示错误，需要安卓7.0才能运行脚本
安卓5 还有救吗，能适配吗

**Comment by ErazerControl** [comment]
> double11v2.0.0,
> 到店铺后提示错误，需要安卓7.0才能运行脚本
> 安卓5 还有救吗，能适配吗

没救了..这些操作需要安卓7.0以上才支持
