### ISSUE TITLE
很多函数没有

### ISSUE THREAD

**Issue by gaoljhy** [ErazerControl/2019double11#28]
indexinParents
waitFor 等等,我是不是没有导入库的问题?

**Comment by ErazerControl** [comment]
> indexinParents
> waitFor 等等,我是不是没有导入库的问题?

你是在手机上的auto.js应用里运行的脚本吗？

**Comment by zhangfaxin** [comment]
maybe

**Comment by gaoljhy** [comment]
> > indexinParents
> > waitFor 等等,我是不是没有导入库的问题?
> 
> 你是在手机上的auto.js应用里运行的脚本吗？

是的

**Comment by YeohWah** [comment]
auto.js4.1没问题  新版8.0去除了一些软件的无障碍

**Comment by ErazerControl** [comment]
> auto.js4.1没问题 新版8.0去除了一些软件的无障碍

那应该就是这样了，我用的是auto.js4.1

**Comment by gaoljhy** [comment]
thanks,i solve it with auto.js4.1
