### ISSUE TITLE
我收集了31家喵铺

### ISSUE THREAD

**Issue by p-jie** [ErazerControl/2019double11#31]
【adidas官方旗舰店】￥u88QYJnWMoD￥
【GIORGIO ARMANI阿玛尼美妆官方旗舰店】￥Z5CSYJnPj80￥
【百雀羚旗舰店】￥6Bp3YJnlLv9￥
【宝洁官方旗舰店】￥82fzYJnNZB6￥
【dyson戴森官方旗舰店】￥S67JYJnKaCA￥
【GREE格力官方旗舰店】￥Q16dYJnqfaK￥
【HomeFacialPro旗舰店】￥bE8HYJnr70O￥
【华为官方旗舰店】￥GGW3YJnsw9R￥
【海尔官方旗舰店】￥IEgYYJntz7B￥
【KIEHL'S科颜氏官方旗舰店】￥sM0vYJnufEr￥
【HR赫莲娜官方旗舰店】￥SHNIYJnxtmr￥
【Lancome兰蔻官方旗舰店】￥AplEYJnCzEb￥
【李宁官方网店】￥Aqc0YJnBUry￥
【蒙牛旗舰店】￥62dKYJnzC3Z￥
【美的官方旗舰店】￥5IZWYJMZskD￥
【美特斯邦威官方网店】￥4M1MYJM68Fl￥
【NIKE官方旗舰店】￥iVROYJM74EB￥
【olay官方旗舰店】￥Kxq4YJMi6HE￥
【OPPO官方旗舰店】￥puPCYJMRR4s￥
【奥克斯旗舰店】￥T1nvYJMjxK1￥
【欧莱雅官方旗舰店】￥zGUAYJMQk8C￥
【荣耀官方旗舰店】￥djmWYJMlJIO￥
【苏泊尔官方旗舰店】￥xzsbYJMmmAp￥
【SK-II官方旗舰店】￥fJQ9YJMnkmJ￥
【vivo官方旗舰店】￥LrcrYJMMAY0￥
【小米官方旗舰店】￥gutyYJMKFal￥
【YSL圣罗兰美妆官方旗舰店】￥Y4D2YJMJcd5￥
【Estee Lauder雅诗兰黛官方旗舰店】￥z2spYJMHlpf￥
【自然堂旗舰店】￥dmugYJMrwRU￥
【ZARA官方旗舰店】￥PCaMYJMuYGs￥
【波司登官方旗舰店】￥FTI5YrYTMQI￥

**Comment by zhaokera** [comment]
作者能把新店加下吗~

**Comment by ErazerControl** [comment]
对比了一下，下个版本将会增加【NIKE官方旗舰店】【HomeFacialPro旗舰店】

**Comment by daxinnan** [comment]
我搜了一下，耐克也没有领喵币啊

**Comment by p-jie** [comment]
> 对比了一下，下个版本将会增加【NIKE官方旗舰店】【HomeFacialPro旗舰店】

我看了一下你搜索的店铺  不是所有的店铺都有喵币领  但是可能复制口令的会好很多 少很多步骤

**Comment by daxinnan** [comment]
> > 对比了一下，下个版本将会增加【NIKE官方旗舰店】【HomeFacialPro旗舰店】
> 
> 我看了一下你搜索的店铺 不是所有的店铺都有喵币领 但是可能复制口令的会好很多 少很多步骤

我这边看的除了Nike，其他列表里的店铺签到都有
