### ISSUE TITLE
每次都提示发现风险 请谨慎安装  

### ISSUE THREAD

**Issue by lixuedong1024** [ErazerControl/2019double11#34]
为什么会出现这个提示

**Comment by ErazerControl** [comment]
> 为什么会出现这个提示
终于有人提问安全性的问题了，其实也是我最担心的，毕竟这么多人用，首先，我也只能保证的是我写的脚本代码没有任何安全性的问题，其次，我在autojs千人的交流群找的autojs.apk以及打包apk的插件，这两个我不敢保证他们是否安全。
不管怎么说，确实得谨慎使用，后果自负啊:)
ps:我个人以及周围朋友都是使用的此脚本，暂未发现有什么异常

**Comment by lixuedong1024** [comment]
您好，首先我不是做安卓开发的我不太清楚啊   
我想咨询下 是只要用了auto.js打包的软件都会报这个警告吗

**Comment by ErazerControl** [comment]
> 您好，首先我不是做安卓开发的我不太清楚啊
> 我想咨询下 是只要用了auto.js打包的软件都会报这个警告吗

我也不知道..我这是这几天才学的..没用auto.js打包过其他软件

**Comment by lixuedong1024** [comment]
soga 好吧
