### ISSUE TITLE
apk偷偷给你盖楼啊

### ISSUE THREAD

**Issue by daxinnan** [ErazerControl/2019double11#36]
调试代码挺不容易的，但是也不应该啥也不说吧，项目里的js脚本没有添加盖楼代码，apk里面店铺签到完就自动给你盖。。

**Comment by ErazerControl** [comment]
> 调试代码挺不容易的，但是也不应该啥也不说吧，项目里的js脚本没有添加盖楼代码，apk里面店铺签到完就自动给你盖。。

很抱歉。。我将在今晚发布新版本的readme做声明
