### ISSUE TITLE
店铺签到不完全

### ISSUE THREAD

**Issue by RebornL** [ErazerControl/2019double11#41]
你好，ErazerControl，我有一个小建议，就是可以直接遍历喵铺下方可签到的店铺，然后获取到一系列可签到店铺名，比内置的店铺名拓展性更好一点。

**Comment by ErazerControl** [comment]
> 你好，ErazerControl，我有一个小建议，就是可以直接遍历喵铺下方可签到的店铺，然后获取到一系列可签到店铺名，比内置的店铺名拓展性更好一点。

谢谢你的小建议，不知道您的意思是不是在喵铺下方点进去签到呢？我们之前想过这样，不过因为觉得喵铺下方的店铺不是特别全所以就采用搜索店铺的方法解决的。

**Comment by RebornL** [comment]
> > 你好，ErazerControl，我有一个小建议，就是可以直接遍历喵铺下方可签到的店铺，然后获取到一系列可签到店铺名，比内置的店铺名拓展性更好一点。
> 
> 谢谢你的小建议，不知道您的意思是不是在喵铺下方点进去签到呢？我们之前想过这样，不过因为觉得喵铺下方的店铺不是特别全所以就采用搜索店铺的方法解决的。

就是可以抓取下方中出现的店铺名，然后将其加入到已有的内置店铺名中，这样就可以扩大可签到的店铺名。最好就是将内置店铺名作为单独的文件，每次就从网络上更新这个可签到店铺名文件，这样就不用重新打包app，只需要更新店铺名文件。这是我的想法，希望能对你有所帮助，谢谢！

**Comment by ErazerControl** [comment]
> > > 你好，ErazerControl，我有一个小建议，就是可以直接遍历喵铺下方可签到的店铺，然后获取到一系列可签到店铺名，比内置的店铺名拓展性更好一点。
> > 
> > 
> > 谢谢你的小建议，不知道您的意思是不是在喵铺下方点进去签到呢？我们之前想过这样，不过因为觉得喵铺下方的店铺不是特别全所以就采用搜索店铺的方法解决的。
> 
> 就是可以抓取下方中出现的店铺名，然后将其加入到已有的内置店铺名中，这样就可以扩大可签到的店铺名。最好就是将内置店铺名作为单独的文件，每次就从网络上更新这个可签到店铺名文件，这样就不用重新打包app，只需要更新店铺名文件。这是我的想法，希望能对你有所帮助，谢谢！

明白您的意思了！我会在以后的版本尝试用您的这个想法，感谢您提供的宝贵思路~  :grin::grin:

**Comment by ErazerControl** [comment]
借助您的建议，在double11qd版试用了该想法~再次感谢您
