### ISSUE TITLE
浏览店铺找不到签到位置

### ISSUE THREAD

**Issue by aeolod998** [ErazerControl/2019double11#43]
![微信图片_20191101225620](https://user-images.githubusercontent.com/43951805/68033894-9d721100-fcfb-11e9-8c47-146cd1901cf4.jpg)

**Comment by ErazerControl** [comment]
淘宝十一月份大更新之后，店铺的很多按钮变位置了，将在下一个版本更新

**Comment by ErazerControl** [comment]
已经发布会店铺签到版double11qdv1.0.0
