### ISSUE TITLE
我想知道作者队伍都多少楼啊

### ISSUE THREAD

**Issue by imuccc** [ErazerControl/2019double11#46]
得几十万楼吧??

**Comment by imuccc** [comment]
对面好惨啊.哈哈哈哈,说不定对面的人还得给你助力

**Comment by ErazerControl** [comment]
> 对面好惨啊.哈哈哈哈,说不定对面的人还得给你助力

2k+...今天还要输了。。

**Comment by imuccc** [comment]
怎么会啊,我们每一个用你插件的都得给你助力的...你把给你助力写到最前面吧.上来先给你助力

**Comment by ErazerControl** [comment]
> 怎么会啊,我们每一个用你插件的都得给你助力的...你把给你助力写到最前面吧.上来先给你助力

感谢你的支持..我不敢保证以后都不会给我助力提前，至少我现在的理念是，大家享受完我的服务再服务于我，人总是会变的，但我希望能一直坚持这个理念。
