### ISSUE TITLE
请问楼主有打包的插件么

### ISSUE THREAD

**Issue by chainingning** [ErazerControl/2019double11#47]
lz有autojs的打包插件么，自己也写了一个，但是没插件，邮箱ning.chai@qq.com。如果有阔步阔以发给小弟，蟹蟹

**Comment by ErazerControl** [comment]
> lz有autojs的打包插件么，自己也写了一个，但是没插件，邮箱[ning.chai@qq.com](mailto:ning.chai@qq.com)。如果有阔步阔以发给小弟，蟹蟹

不好意思，最近比较忙，希望https://zhuanlan.zhihu.com/p/90065914可以帮助到你
