### ISSUE TITLE
开启无障碍服务后卡屏，强制重启后卡在开机动画了

### ISSUE THREAD

**Issue by TensorLake** [ErazerControl/2019double11#7]
如题，期间magisk自动拒绝了root权限。求助！！！

**Comment by ErazerControl** [comment]
> 如题，期间magisk自动拒绝了root权限。求助！！！

老哥，这个我不懂了..

**Comment by TensorLake** [comment]
> 
> 
> > 如题，期间magisk自动拒绝了root权限。求助！！！
> 
> 老哥，这个我不懂了..
