### ISSUE TITLE
领喵币的按钮的变动

### ISSUE THREAD

**Issue by ShmilyChen** [ErazerControl/2019double11#8]
在我手机上这个由`indexInParent(5).depth(18)`变为了`indexInParent(5).depth(14)`
不知道是不是个例，还是淘宝会定时改动这个按钮的depth值

**Comment by ErazerControl** [comment]
> 在我手机上这个由`indexInParent(5).depth(18)`变为了`indexInParent(5).depth(14)`
> 不知道是不是个例，还是淘宝会定时改动这个按钮的depth值

我周围人都可以点击到领喵币的按钮，确定下手机淘宝是否是最新版？

**Comment by ShmilyChen** [comment]
> > 在我手机上这个由`indexInParent(5).depth(18)`变为了`indexInParent(5).depth(14)`
> > 不知道是不是个例，还是淘宝会定时改动这个按钮的depth值
> 
> 我周围人都可以点击到领喵币的按钮，确定下手机淘宝是否是最新版？

我本来是谷歌版，我还专门更新成了最新
不过也无所谓，自己改一下就行了也不影响使用

**Comment by ErazerControl** [comment]
> > > 在我手机上这个由`indexInParent(5).depth(18)`变为了`indexInParent(5).depth(14)`
> > > 不知道是不是个例，还是淘宝会定时改动这个按钮的depth值
> > 
> > 
> > 我周围人都可以点击到领喵币的按钮，确定下手机淘宝是否是最新版？
> 
> 我本来是谷歌版，我还专门更新成了最新
> 不过也无所谓，自己改一下就行了也不影响使用

棒棒哒:thumbsup::thumbsup:
